### PR TITLE
Fix path for nginx redirect

### PR DESCRIPTION
**Pull request by samuelson**

### CODE REVIEW

**Comment by binford2k** [comment]
rather than bouncing back and forth on the trailing slash, can we figure out how to fix nginx so it doesn't redirect? The reason it never loads is that it redirects to a URL with the trailing slash, but without the port.

http://services-uswest.skytap.com:16990/shell/login -> http://services-uswest.skytap.com/shell/login/

**Comment by carthik** [comment]
@samuelson : Any updates or thoughts on this?

**Comment by samuelson** [comment]
@carthik this should be merged. We fixed the underlying issue so it's a bit irrelevant, but this PR is technically correct, which is the best kind of correct.

**Comment by carthik** [comment]
@binford2k if you think that's the worst kind of correct, call me at 1-800-DATMERGE please. :)

**Pull request merged**
